# Library

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Data

In [3]:
data = pd.read_csv('apartments_for_rent_classified_10K.csv', sep = ";", encoding='cp1252')
#C:\Users\ville\Documents\ml_projects\apartment\apartments_for_rent_classified_10K.csv
data

id                category  \
0     5668626895  housing/rent/apartment   
1     5664597177  housing/rent/apartment   
2     5668626833  housing/rent/apartment   
3     5659918074  housing/rent/apartment   
4     5668626759  housing/rent/apartment   
...          ...                     ...   
9995  5630240092  housing/rent/apartment   
9996  5668640983  housing/rent/apartment   
9997  5668643292  housing/rent/apartment   
9998  5668662559  housing/rent/apartment   
9999  5509132540  housing/rent/apartment   

                                                  title  \
0     Studio apartment 2nd St NE, Uhland Terrace NE,...   
1                     Studio apartment 814 Schutte Road   
2     Studio apartment N Scott St, 14th St N, Arling...   
3                        Studio apartment 1717 12th Ave   
4     Studio apartment Washington Blvd, N Cleveland ...   
...                                                 ...   
9995                 Five BR 5407 Abbott Place - Abbott   
9996                            Six BR 256 Las Entradas   
9997                        Six BR 9908 Bentcross Drive   
9998                        One BR in New York NY 10069   
9999         Beautiful Lawrenceville Apartment for rent   

                                                   body  \
0     This unit is located at second St NE, Uhland T...   
1     This unit is located at 814 Schutte Road, Evan...   
2     This unit is located at N Scott St, 14th St N,...   
3     This unit is located at 1717 12th Ave, Seattle...   
4     This unit is located at Washington Blvd, N Cle...   
...                                                 ...   
9995  This unit is located at 5407 Abbott Place - Ab...   
9996  This unit is located at 256 Las Entradas, Mont...   
9997  This unit is located at 9908 Bentcross Drive, ...   
9998  Monthly Rent$4,605 -to $4,790AmenitiesThe Aldy...   
9999  Square footage: 880 sq. feet, unit number: 150...   

                                              amenities  bathrooms  bedrooms  \
0                                                   NaN        NaN       0.0   
1                                                   NaN        NaN       1.0   
2                                                   NaN        1.0       0.0   
3                                                   NaN        1.0       0.0   
4                                                   NaN        NaN       0.0   
...                                                 ...        ...       ...   
9995                                                NaN        4.0       5.0   
9996                                                NaN        8.0       6.0   
9997                                                NaN        8.5       6.0   
9998  Basketball,Cable or Satellite,Doorman,Hot Tub,...        NaN       1.0   
9999                                     Gym,Patio/Deck        1.0       1.0   

     currency fee  has_photo  ... price_display  price_type square_feet  \
0         USD  No  Thumbnail  ...          $790     Monthly         101   
1         USD  No  Thumbnail  ...          $425     Monthly         106   
2         USD  No  Thumbnail  ...        $1,390     Monthly         107   
3         USD  No  Thumbnail  ...          $925     Monthly         116   
4         USD  No  Thumbnail  ...          $880     Monthly         125   
...       ...  ..        ...  ...           ...         ...         ...   
9995      USD  No  Thumbnail  ...        $6,000     Monthly        6300   
9996      USD  No  Thumbnail  ...       $25,000     Monthly        8716   
9997      USD  No  Thumbnail  ...       $11,000     Monthly       11318   
9998      USD  No  Thumbnail  ...        $4,790     Monthly       40000   
9999      USD  No         No  ...        $1,009     Monthly         880   

                        address       cityname state latitude longitude  \
0                           NaN     Washington    DC  38.9057  -76.9861   
1                814 Schutte Rd     Evansville    IN  3

In [3]:
data.shape

(10000, 22)

In [4]:
data.isnull().sum()

id                  0
category            0
title               0
body                0
amenities        3549
bathrooms          34
bedrooms            7
currency            0
fee                 0
has_photo           0
pets_allowed     4163
price               0
price_display       0
price_type          0
square_feet         0
address          3327
cityname           77
state              77
latitude           10
longitude          10
source              0
time                0
dtype: int64

In [5]:
data.isnull().sum()/10000

id               0.0000
category         0.0000
title            0.0000
body             0.0000
amenities        0.3549
bathrooms        0.0034
bedrooms         0.0007
currency         0.0000
fee              0.0000
has_photo        0.0000
pets_allowed     0.4163
price            0.0000
price_display    0.0000
price_type       0.0000
square_feet      0.0000
address          0.3327
cityname         0.0077
state            0.0077
latitude         0.0010
longitude        0.0010
source           0.0000
time             0.0000
dtype: float64

In [6]:
data.dtypes

id                 int64
category          object
title             object
body              object
amenities         object
bathrooms        float64
bedrooms         float64
currency          object
fee               object
has_photo         object
pets_allowed      object
price              int64
price_display     object
price_type        object
square_feet        int64
address           object
cityname          object
state             object
latitude         float64
longitude        float64
source            object
time               int64
dtype: object

In [7]:
data.columns

Index(['id', 'category', 'title', 'body', 'amenities', 'bathrooms', 'bedrooms',
       'currency', 'fee', 'has_photo', 'pets_allowed', 'price',
       'price_display', 'price_type', 'square_feet', 'address', 'cityname',
       'state', 'latitude', 'longitude', 'source', 'time'],
      dtype='object')

In [8]:
for col in data.columns:
    #print(data[col].dtype)
    if data[col].dtype == 'float64':
        print(col,": ",data[col].describe())
    elif data[col].dtype == 'object':
        print(col,": ",np.unique(data[col].astype("str"), return_counts= True ))

category :  (array(['housing/rent/apartment', 'housing/rent/home',
       'housing/rent/short_term'], dtype=object), array([9996,    2,    2], dtype=int64))
title :  (array(['$1,010 / Two BR - Great Deal. MUST SEE. Pet OK!',
       '$1,010/mo - ready to move in.',
       '$1,010/mo, Apex - must see to believe.', ...,
       'proximity and design are everything. Single Car Garage!',
       'tip of Washington DC, sits comfortably in downtown Silver Spring, MD. Pet OK!',
       'wood Apartments for rent in Colorado Springs, Colorado.'],
      dtype=object), array([1, 1, 1, ..., 1, 1, 1], dtype=int64))
body :  (array(['! ACT NOW! 1 mon FREE RENT! NO SECURITY DEPOSIT REQUIRED! This unit features 3 bedrooms, 2 bathrooms, garage for 1 car, finished basement at 1870 square ft Washer dryer hookups rentals available for $45 per month. Snow removal & lawn care are included. Centrally located near shopping and restaurants. Call 989-374-X or email Listedbuy. com to schedule a viewing. Single family

In [9]:
px.histogram(data['price'])

In [22]:
px.histogram(data['bedrooms'])

In [23]:
px.histogram(data['bathrooms'])

In [24]:
px.histogram(data['square_feet'])

## Check for outliers

In [25]:
px.box(data, y = 'price')

In [191]:
len(data[data['price']>5500]), len(data[data['price']>5500])/10000

(68, 0.0068)

In [12]:
data[data['price']>5500]

id                category  \
5052  5668629677  housing/rent/apartment   
6257  5664572322  housing/rent/apartment   
7129  5664572309  housing/rent/apartment   
7436  5659914580  housing/rent/apartment   
7806  5668613099  housing/rent/apartment   
...          ...                     ...   
9990  5659901599  housing/rent/apartment   
9993  5668627239  housing/rent/apartment   
9995  5630240092  housing/rent/apartment   
9996  5668640983  housing/rent/apartment   
9997  5668643292  housing/rent/apartment   

                                     title  \
5052                  One BR 300 Folsom St   
6257               Two BR 2115 Hyde Street   
7129  Studio apartment 1305 Lombard Street   
7436                One BR 9265 Burton Way   
7806             One BR 2097 Market Street   
...                                    ...   
9990               Four BR 864 Teakwood Rd   
9993           Five BR 18605 Avenue Monaco   
9995    Five BR 5407 Abbott Place - Abbott   
9996               Six BR 256 Las Entradas   
9997           Six BR 9908 Bentcross Drive   

                                                   body  \
5052  This unit is located at 300 Folsom St, San Fra...   
6257  This unit is located at 2115 Hyde Street, San ...   
7129  This unit is located at 1305 Lombard Street, S...   
7436  This unit is located at 9265 Burton Way, Bever...   
7806  This unit is located at 2097 Market Street, Sa...   
...                                                 ...   
9990  This unit is located at 864 Teakwood Rd, Los A...   
9993  This unit is located at 18605 Avenue Monaco, L...   
9995  This unit is located at 5407 Abbott Place - Ab...   
9996  This unit is located at 256 Las Entradas, Mont...   
9997  This unit is located at 9908 Bentcross Drive, ...   

                                 amenities  bathrooms  bedrooms currency fee  \
5052                                   NaN        1.0       1.0      USD  No   
6257                          Refrigerator        1.0       2.0      USD  No   
7129               Dishwasher,Refrigerator        1.0       0.0      USD  No   
7436                                   NaN        1.0       1.0      USD  No   
7806                          Refrigerator        1.0       1.0      USD  No   
...                                    ...        ...       ...      ...  ..   
9990  Dishwasher,Parking,Pool,Refrigerator        5.0       4.0      USD  No   
9993          Dishwasher,Pool,Refrigerator        5.0       5.0      USD  No   
9995                                   NaN        4.0       5.0      USD  No   
9996                                   NaN        8.0       6.0      USD  No   
9997                                   NaN        8.5       6.0      USD  No   

      has_photo  ... price_display  price_type square_feet  \
5052  Thumbnail  ...        $5,525     Monthly         809   
6257  Thumbnail  ...        $6,500     Monthly         931   
7129  Thumbnail  ...        $6,500     Monthly        1045   
7436  Thumbnail  ...        $6,200     Monthly        1100   
7806  Thumbnail  ...        $5,900     Monthly        1149   
...         ...  ...           ...         ...         ...   
9990  Thumbnail  ...       $19,500     Monthly        5000   
9993  Thumbnail  ...        $6,900     Monthly        5700   
9995  Thumbnail  ...        $6,000     Monthly        6300   
9996  Thumbnail  ...       $25,000     Monthly        8716   
9997  Thumbnail  ...       $11,000     Monthly       11318   

                        address       cityname state latitude longitude  \
5052              300 Folsom St  San Francisco    CA  37.7599 -122.4379   
6257               2115 Hyde St  San Francisco    CA  37.7599 -122.4379   
7129            1305 Lombard St  San Francisco    CA  37.7599 -122.4379   
7436            9265 Burton Way  Beverly Hills    CA  34.0806 -118.4029   
7806             2097 Market St  San Francisco    CA  37.7599 -122.4379   
...                         ...            ...   ...      ...      

In [4]:
outliers_price = data[data['price']>5500].index

In [37]:
px.box(data, y = 'square_feet')

In [40]:
len(data[data['square_feet']>4000]), len(data[data['square_feet']>4000])/10000

(27, 0.0027)

In [5]:
outliers_square_feet = data[data['square_feet']>4000].index

In [41]:
px.box(data, y = 'bedrooms')

In [44]:
len(data[data['bedrooms']>=6]), len(data[data['bedrooms']>=6])/10000

(21, 0.0021)

In [6]:
outliers_bedrooms = data[data['bedrooms']>=6].index

In [45]:
px.box(data, y = 'bathrooms')

In [46]:
len(data[data['bathrooms']>3.5]), len(data[data['bathrooms']>3.5])/10000

(72, 0.0072)

In [7]:
outliers_bathrooms = data[data['bathrooms']>3.5].index

In [16]:
type(outliers_bedrooms)

pandas.core.indexes.base.Index

In [8]:
outliers = outliers_bedrooms.tolist()+outliers_bathrooms.tolist()+outliers_price.tolist()+outliers_square_feet.tolist()
outliers = set(outliers)
outliers

{5052,
 6257,
 7129,
 7436,
 7806,
 7808,
 7906,
 7907,
 8047,
 8081,
 8206,
 8220,
 8371,
 8477,
 8573,
 8581,
 8707,
 8829,
 8844,
 8887,
 8978,
 9048,
 9128,
 9227,
 9275,
 9276,
 9319,
 9334,
 9347,
 9374,
 9380,
 9402,
 9424,
 9483,
 9485,
 9517,
 9521,
 9527,
 9541,
 9547,
 9567,
 9634,
 9635,
 9639,
 9649,
 9662,
 9685,
 9702,
 9707,
 9725,
 9727,
 9730,
 9731,
 9734,
 9740,
 9749,
 9757,
 9763,
 9770,
 9781,
 9797,
 9810,
 9813,
 9825,
 9840,
 9847,
 9854,
 9861,
 9864,
 9872,
 9879,
 9880,
 9888,
 9892,
 9898,
 9903,
 9904,
 9910,
 9914,
 9917,
 9922,
 9923,
 9924,
 9926,
 9929,
 9932,
 9934,
 9936,
 9938,
 9940,
 9943,
 9945,
 9946,
 9947,
 9954,
 9955,
 9959,
 9964,
 9965,
 9966,
 9967,
 9968,
 9969,
 9970,
 9972,
 9973,
 9974,
 9975,
 9976,
 9977,
 9978,
 9979,
 9980,
 9981,
 9982,
 9983,
 9984,
 9985,
 9986,
 9987,
 9988,
 9989,
 9990,
 9991,
 9992,
 9993,
 9994,
 9995,
 9996,
 9997,
 9998}

In [8]:
len(outliers)

131

In [9]:
data_no_outliers = data.drop(index=outliers, inplace=False)
data_no_outliers.shape

(9869, 22)

## X variables

In [20]:
data.shape

(10000, 22)

In [21]:
data.columns[[1,5,6,11,13,14,16,17]]

Index(['category', 'bathrooms', 'bedrooms', 'price', 'price_type',
       'square_feet', 'cityname', 'state'],
      dtype='object')

In [10]:
x_var = data.iloc[:,[1,5,6,11,13,14,16,17]].dropna(axis=0).values
x_var

array([['housing/rent/apartment', 1.0, 0.0, ..., 107, 'Arlington', 'VA'],
       ['housing/rent/apartment', 1.0, 0.0, ..., 116, 'Seattle', 'WA'],
       ['housing/rent/apartment', 1.0, 0.0, ..., 130, 'Manhattan', 'NY'],
       ...,
       ['housing/rent/apartment', 8.0, 6.0, ..., 8716, 'Montecito', 'CA'],
       ['housing/rent/apartment', 8.5, 6.0, ..., 11318, 'Potomac', 'MD'],
       ['housing/rent/apartment', 1.0, 1.0, ..., 880, 'Lawrenceville',
        'GA']], dtype=object)

In [23]:
x_var.shape

(9883, 8)

In [24]:
x_var[0]

array(['housing/rent/apartment', 1.0, 0.0, 1390, 'Monthly', 107,
       'Arlington', 'VA'], dtype=object)

In [11]:
label_enconder_category     = LabelEncoder()
label_enconder_price_type   = LabelEncoder()
label_enconder_cityname     = LabelEncoder()
label_enconder_state        = LabelEncoder()

x_var[:,0]  = label_enconder_category.fit_transform(x_var[:,0])
x_var[:,4]  = label_enconder_price_type.fit_transform(x_var[:,4])
x_var[:,6]  = label_enconder_cityname.fit_transform(x_var[:,6])
x_var[:,7]  = label_enconder_state.fit_transform(x_var[:,7])

In [26]:
x_var[0]

array([0, 1.0, 0.0, 1390, 0, 107, 52, 45], dtype=object)

### X var with no outliers

In [27]:
data_no_outliers.shape

(9869, 22)

In [12]:
x_var_out = data_no_outliers.iloc[:,[1,5,6,11,13,14,16,17]].dropna(axis=0).values
x_var_out

array([['housing/rent/apartment', 1.0, 0.0, ..., 107, 'Arlington', 'VA'],
       ['housing/rent/apartment', 1.0, 0.0, ..., 116, 'Seattle', 'WA'],
       ['housing/rent/apartment', 1.0, 0.0, ..., 130, 'Manhattan', 'NY'],
       ...,
       ['housing/rent/apartment', 3.5, 5.0, ..., 3748, 'Lawrenceville',
        'GA'],
       ['housing/rent/apartment', 3.5, 5.0, ..., 4000, 'Saint Leonard',
        'MD'],
       ['housing/rent/apartment', 1.0, 1.0, ..., 880, 'Lawrenceville',
        'GA']], dtype=object)

In [29]:
x_var_out.shape

(9753, 8)

In [13]:
x_var_out[:,0]  = label_enconder_category.fit_transform(x_var_out[:,0])
x_var_out[:,4]  = label_enconder_price_type.fit_transform(x_var_out[:,4])
x_var_out[:,6]  = label_enconder_cityname.fit_transform(x_var_out[:,6])
x_var_out[:,7]  = label_enconder_state.fit_transform(x_var_out[:,7])

In [31]:
x_var_out[0]

array([0, 1.0, 0.0, 1390, 0, 107, 52, 45], dtype=object)

### Scale variable

In [14]:
scaler = StandardScaler()
x_var = scaler.fit_transform(x_var)
x_var_out = scaler.fit_transform(x_var_out)

In [33]:
x_var

array([[-1.64285248e-02, -6.17773505e-01, -1.85526539e+00, ...,
        -1.58638084e+00, -1.48245795e+00,  1.20756260e+00],
       [-1.64285248e-02, -6.17773505e-01, -1.85526539e+00, ...,
        -1.56930743e+00,  1.22986960e+00,  1.33777412e+00],
       [-1.64285248e-02, -6.17773505e-01, -1.85526539e+00, ...,
        -1.54274879e+00,  2.09717159e-01,  4.91399262e-01],
       ...,
       [-1.64285248e-02,  1.07457439e+01,  4.51642041e+00, ...,
         1.47452849e+01,  4.30052459e-01, -1.46177348e+00],
       [-1.64285248e-02,  1.15574237e+01,  4.51642041e+00, ...,
         1.96813976e+01,  9.08180060e-01, -4.20081349e-01],
       [-1.64285248e-02, -6.17773505e-01, -7.93317755e-01, ...,
        -1.19964573e-01,  4.22623304e-02, -1.07113893e+00]])

In [34]:
x_var_out

array([[-0.01653768, -0.6437292 , -1.92336732, ..., -1.81846753,
        -1.47458258,  1.20162321],
       [-0.01653768, -0.6437292 , -1.92336732, ..., -1.79826303,
         1.23286055,  1.33217638],
       [-0.01653768, -0.6437292 , -1.92336732, ..., -1.76683381,
         0.21088983,  0.48358081],
       ...,
       [-0.01653768,  3.92828571,  3.67989495, ...,  6.35537483,
         0.04167463, -1.08305717],
       [-0.01653768,  3.92828571,  3.67989495, ...,  6.92110081,
         1.11708173, -0.43029134],
       [-0.01653768, -0.6437292 , -0.80271486, ..., -0.08312555,
         0.04167463, -1.08305717]])

# K-means

In [15]:
wcss2 = []

for k in range(1,20):
    print(k)
    kmeans = KMeans(n_clusters=k,
                    random_state=0)
    kmeans.fit(x_var)
    wcss2.append(kmeans.inertia_)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [36]:
# elbow plot
elbow = px.line(x=range(1,20),y=wcss2) 
for i in range(0,len(wcss2)):
        elbow.add_hline(y=wcss2[i], line_width=1, line_dash="dash", line_color="black")
elbow.show()

k = 2

In [37]:
from sklearn.metrics import silhouette_score

sil = []

# dissimilarity would not be defined for a single cluster, thus, minimum number of clusters should be 2
for k in range(2, 20):
  kmeans = KMeans(n_clusters = k, random_state=0).fit(x_var)
  labels = kmeans.labels_
  sil.append(silhouette_score(x_var, labels, metric = 'euclidean'))

In [38]:
# silhouette plot
px.line(x=range(2,20),y=sil) 

In [15]:
kmeans = KMeans(n_clusters=2,
                    random_state=0)
labels = kmeans.fit_predict(x_var)

In [ ]:
np.unique(labels,return_counts=True)

(array([0, 1]), array([6711, 3172], dtype=int64))

In [ ]:
px.scatter(x = x_var[:,3], #price
           y = x_var[:,5], #square_foot
           color=labels)

In [162]:
data.columns[[1,5,6,11,13,14,16,17]]

Index(['category', 'bathrooms', 'bedrooms', 'price', 'price_type',
       'square_feet', 'cityname', 'state'],
      dtype='object')

In [183]:
px.histogram(data.dropna(subset=['category', 'bathrooms', 'bedrooms', 'price', 'price_type',
       'square_feet', 'cityname', 'state'],axis=0)['square_feet'],color=labels)

# K-means with no outliers

In [39]:
wcss2 = []

for k in range(1,20):
    print(k)
    kmeans = KMeans(n_clusters=k,
                    random_state=0)
    kmeans.fit(x_var_out)
    wcss2.append(kmeans.inertia_)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [40]:
# elbow plot
elbow = px.line(x=range(1,20),y=wcss2) 
for i in range(0,len(wcss2)):
        elbow.add_hline(y=wcss2[i], line_width=1, line_dash="dash", line_color="black")
elbow.show()

In [204]:
from sklearn.metrics import silhouette_score

sil = []

# dissimilarity would not be defined for a single cluster, thus, minimum number of clusters should be 2
for k in range(2, 20):
  kmeans = KMeans(n_clusters = k, random_state=0).fit(x_var_out)
  labels = kmeans.labels_
  sil.append(silhouette_score(x_var_out, labels, metric = 'euclidean'))

In [205]:
# silhouette plot
px.line(x=range(2,20),y=sil) 

k = 2

In [16]:
kmeans = KMeans(n_clusters=2,
                    random_state=0)
labels_out = kmeans.fit_predict(x_var_out)

In [207]:
px.scatter(x = x_var_out[:,3], #price
           y = x_var_out[:,5], #square_foot
           color=labels)

# Writting clusters

In [17]:
labels, labels_out

(array([0, 0, 0, ..., 1, 1, 0]), array([0, 0, 0, ..., 1, 1, 0]))

In [18]:
pd.DataFrame(data=labels).to_csv("10K_cluster.csv")

In [19]:
pd.DataFrame(data=labels_out).to_csv("10K_cluster_nooutliers.csv")